title: Benjamin Yeh

highlighter: rouge
date_format: "%b %-d, %Y"

permalink: /blog/:year:month:day_:title:output_ext

##### COLLECTIONS #####
collections:
  projects:
    output: true
    permalink: /:collection/:path:output_ext

##### SOCIAL INTEGRATION #####
github_username: bentyeh
linkedin_username: bentyeh
twitter_username: bentyeh
scholar_userid: kHslwRwAAAAJ
orcid_id: 0000-0001-9397-6392

##### BUILD SETTINGS #####
incremental: true

include:
  - _pages

exclude:
  - env_ruby.yml
  - LICENSE
  - README.md

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true