title: Benjamin Yeh
description: Stanford BS 2019, MS 2020

highlighter: rouge

##### BUILD SETTINGS #####
incremental: true

include: ['_pages']

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true